// MACHINE GENERATED BY 'go generate' COMMAND; DO NOT EDIT

package syscallx

import "unsafe"
import "syscall"

var _ unsafe.Pointer

var (
	modkernel32 = syscall.NewLazyDLL("kernel32.dll")

	procGetWindowsDirectoryW = modkernel32.NewProc("GetWindowsDirectoryW")
	procGetSystemDirectoryW  = modkernel32.NewProc("GetSystemDirectoryW")
)

func GetWindowsDirectory(buf *uint16, buflen uint32) (n uint32, err error) {
	r0, _, e1 := syscall.Syscall(procGetWindowsDirectoryW.Addr(), 2, uintptr(unsafe.Pointer(buf)), uintptr(buflen), 0)
	n = uint32(r0)
	if n == 0 {
		if e1 != 0 {
			err = error(e1)
		} else {
			err = syscall.EINVAL
		}
	}
	return
}

func GetSystemDirectory(buf *uint16, buflen uint32) (n uint32, err error) {
	r0, _, e1 := syscall.Syscall(procGetSystemDirectoryW.Addr(), 2, uintptr(unsafe.Pointer(buf)), uintptr(buflen), 0)
	n = uint32(r0)
	if n == 0 {
		if e1 != 0 {
			err = error(e1)
		} else {
			err = syscall.EINVAL
		}
	}
	return
}
